name: CI/CD

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  ci-cd:
    name: CI/CD
    uses: StudioLE/Actions/.github/workflows/ci-cd-dioxus-fullstack.yml@v7
    with:
      package_name: alnwick
      binary_name: alnwick
      run_before_test: |
        mkdir -p "${HOME}/.cache/alnwick"
        mkdir -p "${HOME}/.local/share/alnwick"
        cargo run --target "${MATRIX_TARGET}" --package alnwick scrape irl https://irlpodcast.org
        cargo run --target "${MATRIX_TARGET}" --package alnwick download irl --year 2019
        cd packages/dioxus
        npm install
      docker_name: alnwick
      docker_path: docker/cli
    secrets:
      cargo_registry_token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
